kind: PersistentVolume
apiVersion: v1
metadata:
  name: data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/data"
